# Generated by Django 4.2.4 on 2023-09-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_promotion_retailer_productretailer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='product_retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productretailer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='productretailer',
            name='on_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
