# Generated by Django 4.2.4 on 2023-09-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_promotion_product_retailer_alter_product_ean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='product_retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='products.productretailer'),
        ),
    ]
