# Generated by Django 4.2.4 on 2023-09-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_promotion_product_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
