# Generated by Django 4.2.4 on 2023-09-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_retailer_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productretailer',
            unique_together={('product', 'retailer')},
        ),
    ]
