import axios from 'axios';
import React from 'react';
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "./components/ui/table"


class App extends React.Component {
  state = { details: [], }

  componentDidMount() {
    let data;
    axios.get('http://localhost:8000/products/')
      .then(res => {
        data = res.data;
        this.setState({
          details: data
        });
      })
      .catch(err => { })
  }

  render() {
    return (
      <div className='application'>
        <header>Data Generated by Django</header>
        <hr></hr>
        <Table>
  <TableCaption>A list of your recent invoices.</TableCaption>
  <TableHeader>
    <TableRow>
      <TableHead className="w-[100px]">Invoice</TableHead>
      <TableHead>Status</TableHead>
      <TableHead>Method</TableHead>
      <TableHead className="text-right">Amount</TableHead>
    </TableRow>
  </TableHeader>
  <TableBody>
    <TableRow>
      <TableCell className="font-medium">INV001</TableCell>
      <TableCell>Paid</TableCell>
      <TableCell>Credit Card</TableCell>
      <TableCell className="text-right">$250.00</TableCell>
    </TableRow>
  </TableBody>
</Table>

        {this.state.details.map((output, id) => (
          <div key={id}>
            <div>
              <h2>{output.ean}</h2>
              <h3>{output.product_title}</h3>
            </div>
          </div>
        ))}
      </div>
    )
  }
}

export default App;
