import axios from 'axios';
import React from 'react';


class App extends React.Component {
  state = { details: [], }

  componentDidMount() {
    let data;
    axios.get('http://localhost:8000/products/')
    .then(res => {
      data = res.data;
      this.setState({
        details: data
      });
    })
    .catch(err => {} )
  }

  render() {
    return (
      <div>
        <header>Data Generated by Django</header>
        <hr></hr>
        {this.state.details.map((output, id) => (
          <div key={id}>
            <div>
              <h2>{output.ean}</h2>
              <h3>{output.product_title}</h3>
            </div>
          </div>
        ))}
      </div>
    )
  }
}

export default App;
